// GleeWorld Studio premium instrument catalog ("gw:" presets). These are
// self-hosted, velocity-layered sample sets converted from free/open-license
// libraries (see scripts/studio-samples/CREDITS.md), stored in the glee-world
// Space under studio-samples/ and served through the supabase.gleeworld.org
// public-storage proxy — that path already sends Access-Control-Allow-Origin
// (plain Spaces URLs don't) and is allow-listed in the CSP.
//
// Each instrument is described by a manifest.json (see GwManifest) generated
// by scripts/studio-samples/; the engine is fully manifest-driven and never
// hardcodes sample file lists.

export const GW_SAMPLE_BASE =
  'https://supabase.gleeworld.org/storage/v1/object/public/studio-samples';

export interface GwInstrument {
  name: string;          // stable preset name, e.g. 'grand_piano' (stored in sessions)
  label: string;         // picker label, e.g. 'Grand Piano'
  kind: 'pitched' | 'kit';
  // Space folder when it differs from `name`. Samples upload with
  // Cache-Control: immutable, so a rebuild that changes what layer paths
  // MEAN (e.g. the 4→8-velocity-layer grand piano) must publish to a fresh
  // folder — reusing paths would serve stale mixed layers to return visitors.
  dir?: string;
  // GM soundfont instrument to fall back to when the premium manifest can't
  // be fetched (offline bank, renamed instrument). Kits omit it and fall
  // back to the synthesized basic kit instead.
  gmFallback?: string;
}

// Picker order: keyboard → voices → strings → guitars → organ → kits.
export const GW_INSTRUMENTS: GwInstrument[] = [
  { name: 'grand_piano',      label: 'Grand Piano',              kind: 'pitched', gmFallback: 'acoustic_grand_piano', dir: 'grand_piano_v2' },
  { name: 'electric_piano',   label: 'Electric Piano',           kind: 'pitched', gmFallback: 'electric_piano_1' },
  { name: 'choir_aahs',       label: 'Choir Aahs',               kind: 'pitched', gmFallback: 'choir_aahs' },
  { name: 'string_ensemble',  label: 'String Ensemble',          kind: 'pitched', gmFallback: 'string_ensemble_1' },
  { name: 'violin',           label: 'Violin',                   kind: 'pitched', gmFallback: 'violin' },
  { name: 'cello',            label: 'Cello Section',            kind: 'pitched', gmFallback: 'cello' },
  { name: 'pizzicato',        label: 'Pizzicato Strings',        kind: 'pitched', gmFallback: 'pizzicato_strings' },
  { name: 'guitar_nylon',     label: 'Acoustic Guitar',          kind: 'pitched', gmFallback: 'acoustic_guitar_nylon' },
  { name: 'pipe_organ',       label: 'Pipe Organ',               kind: 'pitched', gmFallback: 'church_organ' },
  { name: 'kit_studio',       label: 'Drum Kit · Studio',        kind: 'kit' },
  { name: 'kit_rock',         label: 'Drum Kit · Rock',          kind: 'kit' },
  { name: 'kit_jazz',         label: 'Drum Kit · Jazz',          kind: 'kit' },
  // 808 family (added 2026-08-17): Michael Fischer's 1994 TR-808 set + the
  // CC0 trap kits, converted by scripts/studio-samples from
  // ~/Music/Samples/808 recipes (recipes-808.json). bass_808 is PITCHED —
  // two FFT-tuned long subs (G1/A1) playable chromatically.
  { name: 'kit_808',          label: 'Drum Kit · TR-808',        kind: 'kit' },
  { name: 'kit_trap',         label: 'Drum Kit · Trap',          kind: 'kit' },
  // kit_909 (2026-08-17): ORIGINAL synthesized 909-style kit — no Roland
  // audio anywhere in it (no clean CC0 909 sample set exists). Generated by
  // ~/Music/Samples/909/synth909.py; provenance is wholly ours.
  { name: 'kit_909',          label: 'Drum Kit · 909',           kind: 'kit' },
  { name: 'bass_808',         label: '808 Bass',                 kind: 'pitched', gmFallback: 'synth_bass_2' },
];

export const GW_BY_NAME: Record<string, GwInstrument> =
  Object.fromEntries(GW_INSTRUMENTS.map((g) => [g.name, g]));

// One velocity layer of a pitched instrument: `urls` maps note names
// (e.g. 'C4') to files relative to the instrument folder. A note-on with
// MIDI velocity <= maxVel (1..127) plays from the first matching layer.
export interface GwLayer {
  maxVel: number;
  urls: Record<string, string>;
}

// One velocity layer of a single kit piece (relative file URL).
export interface GwKitHit {
  maxVel: number;
  url: string;
}

export interface GwManifest {
  name: string;
  kind: 'pitched' | 'kit';
  // Encodings available for every sample. `urls` always name .mp3 files
  // (the universal fallback); when 'webm' is listed, a same-path .webm
  // (Opus, ~40% smaller) also exists and capable clients swap extensions.
  formats?: string[];
  // Pitched: velocity layers in ascending maxVel order (last must be 127).
  layers?: GwLayer[];
  // Optional release samples (played briefly on note-off; piano dampers).
  release?: { urls: Record<string, string> };
  // Kit: GM drum MIDI note (as string) → hits in ascending maxVel order.
  kit?: Record<string, GwKitHit[]>;
}

const gwDir = (name: string): string => GW_BY_NAME[name]?.dir ?? name;

export function gwManifestUrl(name: string): string {
  return `${GW_SAMPLE_BASE}/${gwDir(name)}/manifest.json`;
}

export function gwSampleUrl(name: string, relative: string): string {
  // Sample filenames use sharp note names ('l0/C#4.mp3'); an unencoded '#'
  // would start a URL fragment and truncate the request. Encode each path
  // segment, never the separators.
  const encoded = relative.split('/').map(encodeURIComponent).join('/');
  return `${GW_SAMPLE_BASE}/${gwDir(name)}/${encoded}`;
}

// ── webm/opus support probe ──────────────────────────────────────────
//
// Newer sample sets ship each file as .mp3 plus a smaller .webm (Opus).
// Whether Web Audio can decode webm/opus varies (Safari gained it late),
// and canPlayType answers for <audio>, not decodeAudioData — so probe the
// exact capability once: decode a 567-byte silent webm/opus clip. Until
// the async probe resolves, callers get 'mp3' (both encodings exist
// server-side, so a mixed prefix of downloads is harmless).

// 0.02s of silence, 48kHz mono Opus in webm (ffmpeg -f lavfi anullsrc).
const WEBM_OPUS_PROBE =
  'GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQRChYECGFOAZwEAAAAAAAIHEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHYTbuMU6uEElTDZ1OsggFCTbuMU6uEHFO7a1OsggHx7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsirXsYMPQkBNgI1MYXZmNjIuMTIuMTAyV0GNTGF2ZjYyLjEyLjEwMkSJiEA8AAAAAAAAFlSua+WuAQAAAAAAAFzXgQFzxYjRQycHOWoAL5yBACK1nIN1bmSIgQCGhkFfT1BVU1aqg2MuoFa7hATEtACDgQLhkZ+BAbWIQOdwAAAAAABiZIEQY6KTT3B1c0hlYWQBATgBgLsAAAAAABJUw2f9c3OgY8CAZ8iaRaOHRU5DT0RFUkSHjUxhdmY2Mi4xMi4xMDJzc9djwItjxYjRQycHOWoAL2fIokWjh0VOQ09ERVJEh5VMYXZjNjIuMjguMTAyIGxpYm9wdXNnyKFFo4hEVVJBVElPTkSHkzAwOjAwOjAwLjAyODAwMDAwMAAfQ7Z1qOeBAKOLgQAAgAgL5jsjq2CglqGKgQAVAAgIrLMOxpuBB3WihADN/mAcU7trkbuPs4EAt4r3gQHxggHE8IED';

let webmOpusSupported = false;
let probeStarted = false;

function startWebmOpusProbe(): void {
  if (probeStarted) return;
  probeStarted = true;
  try {
    const bytes = Uint8Array.from(atob(WEBM_OPUS_PROBE), (c) => c.charCodeAt(0));
    // OfflineAudioContext: no user-gesture requirement and no audible tap on
    // the live context. decodeAudioData rejects on unsupported containers.
    const ctx = new OfflineAudioContext(1, 1, 48000);
    ctx.decodeAudioData(bytes.buffer)
      .then(() => { webmOpusSupported = true; })
      .catch(() => { /* mp3 fallback stands */ });
  } catch { /* no Web Audio (tests/SSR) — mp3 fallback stands */ }
}

// Best sample encoding for a manifest on this client. Sync by design: it is
// called on the note-on hot path's setup; the probe is kicked off at module
// load and resolves long before any Studio session opens.
export function pickGwSampleFormat(manifest: Pick<GwManifest, 'formats'>): 'mp3' | 'webm' {
  startWebmOpusProbe();
  return webmOpusSupported && (manifest.formats?.includes('webm') ?? false) ? 'webm' : 'mp3';
}

// Rewrite a manifest-relative .mp3 path to the chosen encoding.
export function gwSampleRelForFormat(rel: string, format: 'mp3' | 'webm'): string {
  return format === 'webm' ? rel.replace(/\.mp3$/, '.webm') : rel;
}

startWebmOpusProbe();

// Pick the layer index for a MIDI velocity (1..127): first layer whose
// maxVel covers it; velocities past the last maxVel clamp to the top layer.
export function gwLayerIndexForVelocity(layers: { maxVel: number }[], velocity: number): number {
  for (let i = 0; i < layers.length; i++) {
    if (velocity <= layers[i].maxVel) return i;
  }
  return layers.length - 1;
}

// preset_id encoding, alongside the GM 'gm:' prefix: 'gw:<name>'.
export const GW_PRESET_PREFIX = 'gw:';
export const toGwPresetId = (name: string) => `${GW_PRESET_PREFIX}${name}`;
export const fromGwPresetId = (presetId: string | undefined): string | null =>
  presetId?.startsWith(GW_PRESET_PREFIX) ? presetId.slice(GW_PRESET_PREFIX.length) : null;
