import type { BankQ } from './types';

/**
 * Authored question banks keyed by `${levelId}.${unitSortOrder}`.
 * BankQ: p = prompt, c = correct, w = wrong choices, e = explanation, n = optional notation.
 */
export const BANKS: Record<string, BankQ[]> = {
  // ─── Level 1: Elementary ───
  '1.1': [
    { p: 'A sound that goes from low to high is moving…', c: 'Up', w: ['Down', 'Sideways', 'Nowhere'] },
    { p: 'Loud in music is the opposite of…', c: 'Soft', w: ['Fast', 'High', 'Short'] },
    { p: 'The steady pulse you can clap along to is called the…', c: 'Beat', w: ['Rhythm', 'Melody', 'Rest'] },
    { p: 'The pattern of long and short sounds is called the…', c: 'Rhythm', w: ['Beat', 'Tempo', 'Pitch'], e: 'The beat stays steady; the rhythm changes with the music.' },
    { p: 'A moment of silence in music is shown by a…', c: 'Rest', w: ['Note', 'Bar line', 'Clef'] },
    { p: 'How fast or slow the music goes is called the…', c: 'Tempo', w: ['Dynamics', 'Pitch', 'Meter'] },
    { p: 'How high or low a sound is, is called its…', c: 'Pitch', w: ['Rhythm', 'Volume', 'Beat'] },
    { p: 'When you sing softly, you are changing the…', c: 'Dynamics', w: ['Tempo', 'Pitch', 'Meter'] },
    { p: 'A note makes sound. A rest makes…', c: 'Silence', w: ['Noise', 'An echo', 'A chord'] },
    { p: 'If a melody keeps repeating the same pitch, it is moving…', c: 'Staying the same', w: ['Up', 'Down', 'Backwards'] },
  ],
  '1.2': [
    { p: 'A quarter note ("ta") gets how many beats in 4/4?', c: '1 beat', w: ['2 beats', '4 beats', 'Half a beat'] },
    { p: 'Two paired eighth notes ("ti-ti") together last as long as…', c: 'One quarter note', w: ['One half note', 'One whole note', 'Two quarter notes'] },
    { p: 'A half note gets how many beats in 4/4?', c: '2 beats', w: ['1 beat', '3 beats', '4 beats'] },
    { p: 'A whole note gets how many beats in 4/4?', c: '4 beats', w: ['1 beat', '2 beats', '8 beats'] },
    { p: 'A quarter rest means…', c: 'Silence for 1 beat', w: ['Sound for 1 beat', 'Silence for 4 beats', 'Play louder'] },
    { p: 'How many quarter notes fit in one whole note?', c: '4', w: ['2', '3', '8'] },
    { p: 'How many eighth notes fit in one half note?', c: '4', w: ['2', '6', '8'] },
    { p: 'A whole rest means silence for how many beats in 4/4?', c: '4 beats', w: ['1 beat', '2 beats', '3 beats'] },
    { p: 'Which note is the longest?', c: 'Whole note', w: ['Half note', 'Quarter note', 'Eighth note'] },
    { p: '"Ta ti-ti ta ta" uses how many beats?', c: '4', w: ['3', '5', '6'] },
  ],
  '1.3': [
    { p: 'The music staff has how many lines?', c: '5', w: ['4', '6', '7'] },
    { p: 'The music staff has how many spaces?', c: '4', w: ['5', '3', '6'] },
    { p: 'When notes move up the staff, the sound gets…', c: 'Higher', w: ['Lower', 'Louder', 'Faster'] },
    { p: 'The treble clef is also called the…', c: 'G clef', w: ['F clef', 'C clef', 'B clef'], e: 'Its curl wraps around the G line.' },
    { p: 'A note sitting on a line with the line through its middle is a…', c: 'Line note', w: ['Space note', 'Rest', 'Sharp note'] },
    { p: 'A note that sits between two lines is a…', c: 'Space note', w: ['Line note', 'Ledger note', 'Bar note'] },
    { p: 'The symbol at the start of the staff that sets the note names is the…', c: 'Clef', w: ['Time signature', 'Bar line', 'Key'] },
    { p: 'Staff lines and spaces are counted from…', c: 'Bottom to top', w: ['Top to bottom', 'Left to right', 'Middle out'] },
  ],
  '1.4': [
    { p: 'The treble staff lines spell (bottom to top)…', c: 'E G B D F', w: ['F A C E', 'G B D F A', 'A C E G'] },
    { p: 'The treble staff spaces spell (bottom to top)…', c: 'F A C E', w: ['E G B D', 'A C E G', 'D F A C'] },
    { p: 'Middle C sits…', c: 'On a ledger line below the treble staff', w: ['On the top line', 'In the third space', 'Above the staff'] },
    { p: 'The musical alphabet uses which letters?', c: 'A through G', w: ['A through H', 'A through F', 'C through J'] },
    { p: 'After G, the musical alphabet…', c: 'Starts over at A', w: ['Continues to H', 'Stops', 'Skips to C'] },
  ],
  '1.5': [
    { p: 'The first solfège syllable of a major scale is…', c: 'Do', w: ['Re', 'Sol', 'La'] },
    { p: 'Do, re, mi — which comes next?', c: 'Fa', w: ['Sol', 'La', 'Ti'] },
    { p: 'Moving from one note to the very next (C to D) is a…', c: 'Step', w: ['Skip', 'Repeat', 'Leap'] },
    { p: 'Moving from C up to E (skipping D) is a…', c: 'Skip', w: ['Step', 'Repeat', 'Slide'] },
    { p: 'Singing the same note twice in a row is a…', c: 'Repeat', w: ['Step', 'Skip', 'Rest'] },
    { p: 'The shape of a melody as it rises and falls is its…', c: 'Contour', w: ['Rhythm', 'Tempo', 'Dynamics'] },
    { p: 'The five-note core of many folk songs (do-re-mi-sol-la) is the…', c: 'Pentatonic scale', w: ['Chromatic scale', 'Whole-tone scale', 'Blues scale'] },
    { p: 'Which solfège syllable matches "sol"?', c: 'The 5th note of the scale', w: ['The 1st note', 'The 3rd note', 'The 7th note'] },
  ],
  '1.6': [
    { p: 'The vertical lines that divide the staff into measures are…', c: 'Bar lines', w: ['Ledger lines', 'Staff lines', 'Slurs'] },
    { p: 'The space between two bar lines is a…', c: 'Measure', w: ['Phrase', 'Staff', 'System'] },
    { p: 'In 4/4 time, each measure has how many beats?', c: '4', w: ['3', '2', '8'] },
    { p: 'In 3/4 time, each measure has how many beats?', c: '3', w: ['4', '2', '6'] },
    { p: 'The top number of a time signature tells you…', c: 'Beats per measure', w: ['Which note gets the beat', 'The tempo', 'The key'] },
    { p: 'A double bar line at the very end of a piece means…', c: 'The end', w: ['Repeat', 'Play louder', 'New key'] },
    { p: 'Which time signature gives a waltz feel (1-2-3)?', c: '3/4', w: ['4/4', '2/4', '6/8'] },
    { p: 'In 2/4 time, how many quarter notes fill one measure?', c: '2', w: ['4', '3', '1'] },
  ],
  '1.7': [
    { p: '"Piano" (p) tells you to play…', c: 'Soft', w: ['Loud', 'Fast', 'Slow'] },
    { p: '"Forte" (f) tells you to play…', c: 'Loud', w: ['Soft', 'Slow', 'Smooth'] },
    { p: 'A crescendo means…', c: 'Gradually get louder', w: ['Gradually get softer', 'Speed up', 'Slow down'] },
    { p: 'A decrescendo means…', c: 'Gradually get softer', w: ['Gradually get louder', 'Stop suddenly', 'Repeat'] },
    { p: '"Allegro" is a tempo that is…', c: 'Fast', w: ['Slow', 'Medium soft', 'Silent'] },
    { p: '"Adagio" is a tempo that is…', c: 'Slow', w: ['Fast', 'Very loud', 'Bouncy'] },
    { p: 'A repeat sign tells you to…', c: 'Play the section again', w: ['Stop', 'Skip ahead', 'Play softer'] },
    { p: 'Dynamics in music describe…', c: 'How loud or soft to play', w: ['How fast to play', 'Which notes to play', 'When to breathe'] },
  ],

  // ─── Level 2: Middle ───
  '2.1': [
    { p: 'The bass staff lines spell (bottom to top)…', c: 'G B D F A', w: ['E G B D F', 'A C E G', 'F A C E'] },
    { p: 'The bass staff spaces spell (bottom to top)…', c: 'A C E G', w: ['F A C E', 'G B D F', 'E G B D'] },
    { p: 'The grand staff joins which two clefs?', c: 'Treble and bass', w: ['Treble and alto', 'Bass and tenor', 'Alto and tenor'] },
    { p: 'Middle C on the grand staff sits…', c: 'Between the two staves', w: ['On the top line of the bass staff', 'In the treble third space', 'Below both staves'] },
    { p: 'Short lines that extend the staff above or below are…', c: 'Ledger lines', w: ['Bar lines', 'Slur lines', 'Beam lines'] },
    { p: 'Middle C is also called…', c: 'C4', w: ['C3', 'C5', 'C1'], e: 'Octaves are numbered from C; middle C is the 4th C on a piano.' },
    { p: 'The bass clef is also called the…', c: 'F clef', w: ['G clef', 'C clef', 'D clef'], e: 'Its two dots surround the F line.' },
  ],
  '2.2': [
    { p: 'How many sixteenth notes equal one quarter note?', c: '4', w: ['2', '8', '16'] },
    { p: 'A dot after a note adds…', c: 'Half the note\u2019s value', w: ['One beat', 'Double the value', 'A quarter of the value'] },
    { p: 'A dotted half note in 4/4 lasts…', c: '3 beats', w: ['2 beats', '4 beats', '2½ beats'] },
    { p: 'A dotted quarter note in 4/4 lasts…', c: '1½ beats', w: ['1 beat', '2 beats', '¾ beat'] },
    { p: 'A tie between two notes means…', c: 'Hold them as one longer note', w: ['Play them smoothly but separately', 'Play them staccato', 'Repeat them'] },
    { p: 'A slur between two different pitches means…', c: 'Play them smoothly connected', w: ['Hold as one note', 'Play them detached', 'Skip the second note'] },
    { p: 'Notes before the first full measure are called…', c: 'Pickup notes (anacrusis)', w: ['Grace notes', 'Ledger notes', 'Ghost notes'] },
    { p: 'A quarter note tied to an eighth note lasts…', c: '1½ beats', w: ['2 beats', '1 beat', '2½ beats'] },
    { p: '"Ti-tika" is one eighth followed by…', c: 'Two sixteenths', w: ['Two eighths', 'One sixteenth', 'A quarter'] },
  ],
  '2.3': [
    { p: 'A sharp (♯) does what to a note?', c: 'Raises it a half step', w: ['Lowers it a half step', 'Raises it a whole step', 'Cancels an accidental'] },
    { p: 'A flat (♭) does what to a note?', c: 'Lowers it a half step', w: ['Raises it a half step', 'Lowers it a whole step', 'Holds it longer'] },
    { p: 'A natural (♮) does what?', c: 'Cancels a sharp or flat', w: ['Raises a note', 'Lowers a note', 'Doubles the note'] },
    { p: 'The smallest distance between two keys on a piano is a…', c: 'Half step', w: ['Whole step', 'Skip', 'Third'] },
    { p: 'A whole step equals…', c: 'Two half steps', w: ['One half step', 'Three half steps', 'An octave'] },
    { p: 'F♯ sounds the same as…', c: 'G♭', w: ['G♯', 'E♭', 'F♭'], e: 'Same key, two names: enharmonic equivalents.' },
    { p: 'E to F is a…', c: 'Half step', w: ['Whole step', 'Skip', 'Third'], e: 'E–F and B–C are the natural half steps (no black key between).' },
    { p: 'Which pair of white keys has NO black key between them?', c: 'B and C', w: ['C and D', 'F and G', 'G and A'] },
    { p: 'An accidental applies for how long?', c: 'The rest of that measure', w: ['One note only', 'The whole piece', 'The whole line'] },
  ],
  '2.4': [
    { p: 'The major scale pattern of whole (W) and half (H) steps is…', c: 'W W H W W W H', w: ['W H W W H W W', 'W W W H W W H', 'H W W H W W W'] },
    { p: 'The order of sharps begins…', c: 'F C G D', w: ['B E A D', 'C F G D', 'F G C A'] },
    { p: 'The order of flats begins…', c: 'B E A D', w: ['F C G D', 'E B A D', 'B A E D'] },
    { p: 'To name a sharp key: take the last sharp and go…', c: 'Up a half step', w: ['Down a half step', 'Up a whole step', 'Down a fifth'] },
    { p: 'To name a flat key (two or more flats), look at the…', c: 'Second-to-last flat', w: ['Last flat', 'First flat', 'Third flat'] },
    { p: 'Moving clockwise around the circle of fifths, each key adds…', c: 'One sharp', w: ['One flat', 'Two sharps', 'A minor key'] },
    { p: 'Which major key has no sharps or flats?', c: 'C major', w: ['G major', 'F major', 'A major'] },
  ],
  '2.5': [
    { p: 'A minor key shares its key signature with its…', c: 'Relative major', w: ['Parallel major', 'Dominant', 'Subdominant'] },
    { p: 'The relative minor starts on which degree of the major scale?', c: '6th', w: ['5th', '2nd', '3rd'], e: 'Or: count down 3 half steps from the major tonic.' },
    { p: 'Natural minor compared to major sounds…', c: 'Darker / sadder', w: ['Brighter / happier', 'Identical', 'Out of tune'] },
    { p: 'A natural minor is relative to which major key?', c: 'C major', w: ['A major', 'G major', 'F major'] },
    { p: 'From a major key, find the relative minor by going…', c: 'Down 3 half steps', w: ['Up 3 half steps', 'Down 5 half steps', 'Up a whole step'] },
    { p: 'The natural minor scale pattern is…', c: 'W H W W H W W', w: ['W W H W W W H', 'H W W H W W W', 'W H W H W H W'] },
  ],
  '2.6': [
    { p: 'C up to D is what interval?', c: '2nd', w: ['3rd', 'Unison', '4th'] },
    { p: 'C up to E is what interval?', c: '3rd', w: ['2nd', '4th', '5th'] },
    { p: 'C up to G is what interval?', c: '5th', w: ['4th', '6th', '3rd'] },
    { p: 'Two notes played at the same time form a ______ interval.', c: 'Harmonic', w: ['Melodic', 'Parallel', 'Linear'] },
    { p: 'Two notes played one after another form a ______ interval.', c: 'Melodic', w: ['Harmonic', 'Vertical', 'Blocked'] },
    { p: 'Two voices singing the exact same pitch are at a…', c: 'Unison', w: ['Octave', '2nd', '5th'] },
    { p: 'C4 up to C5 is an…', c: 'Octave', w: ['Unison', '7th', '5th'] },
    { p: 'To find an interval number, count…', c: 'Both notes and every line/space between', w: ['Only the notes between', 'The half steps', 'The sharps'] },
  ],
  '2.7': [
    { p: 'A triad is built from how many notes?', c: '3', w: ['2', '4', '5'] },
    { p: 'A triad is built by stacking…', c: 'Thirds', w: ['Seconds', 'Fourths', 'Fifths'] },
    { p: 'The bottom note of a root-position triad is the…', c: 'Root', w: ['Third', 'Fifth', 'Bass clef'] },
    { p: 'The primary chords in any major key are…', c: 'I, IV, V', w: ['I, II, III', 'ii, iii, vi', 'IV, V, vii'] },
    { p: 'In C major, the I chord is…', c: 'C–E–G', w: ['C–F–A', 'D–F–A', 'G–B–D'] },
    { p: 'In C major, the V chord is…', c: 'G–B–D', w: ['F–A–C', 'C–E–G', 'A–C–E'] },
    { p: 'In C major, the IV chord is…', c: 'F–A–C', w: ['G–B–D', 'C–E–G', 'E–G–B'] },
    { p: 'A major triad compared to a minor triad has a…', c: 'Higher (major) third', w: ['Lower third', 'Different root', 'Different fifth'] },
  ],
  '2.8': [
    { p: '6/8 time is a ______ meter.', c: 'Compound', w: ['Simple', 'Asymmetric', 'Free'] },
    { p: 'In 6/8, the beats group into…', c: 'Two groups of three eighths', w: ['Three groups of two eighths', 'Six equal beats', 'Four groups'] },
    { p: 'Cut time (𝄵) is the same as…', c: '2/2', w: ['4/4', '2/4', '6/8'] },
    { p: 'In simple meter, the beat divides into…', c: 'Two equal parts', w: ['Three equal parts', 'Four unequal parts', 'It never divides'] },
    { p: 'In compound meter, the beat divides into…', c: 'Three equal parts', w: ['Two equal parts', 'Five parts', 'It never divides'] },
    { p: 'A conductor\u2019s pattern for 3/4 has how many motions?', c: '3', w: ['2', '4', '6'] },
    { p: 'Which time signature is simple duple?', c: '2/4', w: ['3/4', '6/8', '9/8'] },
  ],
  '2.9': [
    { p: '"pp" (pianissimo) means…', c: 'Very soft', w: ['Very loud', 'Medium soft', 'Suddenly soft'] },
    { p: '"ff" (fortissimo) means…', c: 'Very loud', w: ['Very soft', 'Medium loud', 'Accented'] },
    { p: '"sfz" (sforzando) means…', c: 'A sudden strong accent', w: ['Gradually louder', 'Very soft', 'Slow down'] },
    { p: 'Staccato dots tell you to play…', c: 'Short and detached', w: ['Smooth and connected', 'Loud', 'Slower'] },
    { p: 'Legato means play…', c: 'Smooth and connected', w: ['Short and detached', 'Very fast', 'With accents'] },
    { p: 'A fermata (𝄐) means…', c: 'Hold the note longer than written', w: ['Cut the note short', 'Repeat the note', 'Silence'] },
    { p: 'Ritardando means…', c: 'Gradually slow down', w: ['Gradually speed up', 'Suddenly stop', 'Return to tempo'] },
    { p: 'Accelerando means…', c: 'Gradually speed up', w: ['Gradually slow down', 'Play louder', 'Hold the note'] },
    { p: '"D.C. al Fine" tells you to…', c: 'Return to the beginning and play to "Fine"', w: ['Skip to the coda', 'Repeat the last measure', 'End immediately'] },
    { p: 'Which tempo term is slowest?', c: 'Largo', w: ['Presto', 'Allegro', 'Moderato'] },
  ],

  // ─── Level 3: High School ───
  '3.1': [
    { p: 'Parallel keys (C major / C minor) share the same…', c: 'Tonic', w: ['Key signature', 'Third', 'Mode'] },
    { p: 'Relative keys (C major / A minor) share the same…', c: 'Key signature', w: ['Tonic', 'Tempo', 'Third'] },
    { p: 'How many major key signatures are there (including enharmonics)?', c: '15', w: ['12', '7', '24'] },
    { p: 'The key one position clockwise from C on the circle of fifths is…', c: 'G major', w: ['F major', 'D major', 'A minor'] },
    { p: 'C♯ major and which key are enharmonically the same?', c: 'D♭ major', w: ['C♭ major', 'B major', 'E♭ major'] },
  ],
  '3.2': [
    { p: 'Harmonic minor raises which scale degree?', c: '7th', w: ['6th', '3rd', '5th'] },
    { p: 'Melodic minor (ascending) raises which degrees?', c: '6th and 7th', w: ['7th only', '3rd and 7th', '2nd and 6th'] },
    { p: 'Melodic minor descending is the same as…', c: 'Natural minor', w: ['Harmonic minor', 'Major', 'Dorian'] },
    { p: 'The chromatic scale uses only…', c: 'Half steps', w: ['Whole steps', 'Thirds', 'Mixed steps'] },
    { p: 'The whole-tone scale has how many different notes?', c: '6', w: ['7', '5', '12'] },
    { p: 'The major pentatonic scale omits which degrees of the major scale?', c: '4th and 7th', w: ['2nd and 6th', '3rd and 5th', '1st and 5th'] },
    { p: 'The blues scale adds which "blue note" to the minor pentatonic?', c: 'Lowered 5th (♭5)', w: ['Raised 7th', 'Lowered 2nd', 'Raised 4th only in major'] },
    { p: 'Which mode is identical to the natural minor scale?', c: 'Aeolian', w: ['Dorian', 'Ionian', 'Mixolydian'] },
    { p: 'Which mode is identical to the major scale?', c: 'Ionian', w: ['Lydian', 'Aeolian', 'Phrygian'] },
  ],
  '3.3': [
    { p: 'Inverting a major 3rd gives a…', c: 'Minor 6th', w: ['Major 6th', 'Minor 3rd', 'Perfect 4th'], e: 'Inversions: number adds to 9; major ↔ minor.' },
    { p: 'Inverting a perfect 4th gives a…', c: 'Perfect 5th', w: ['Perfect 4th', 'Major 5th', 'Tritone'], e: 'Perfect stays perfect.' },
    { p: 'A compound interval is…', c: 'Larger than an octave', w: ['Smaller than an octave', 'Two intervals at once', 'A dissonance'] },
    { p: 'The tritone divides the octave into…', c: 'Two equal halves', w: ['Three parts', 'A fifth and a fourth', 'Unequal thirds'] },
    { p: 'The tritone in a V7 chord resolves: leading tone moves…', c: 'Up to the tonic', w: ['Down to the dominant', 'Down a third', 'Nowhere'] },
    { p: 'A major interval made one half step smaller becomes…', c: 'Minor', w: ['Diminished', 'Augmented', 'Perfect'] },
    { p: 'A perfect interval made one half step larger becomes…', c: 'Augmented', w: ['Major', 'Minor', 'Doubly perfect'] },
  ],
  '3.4': [
    { p: 'A dominant seventh chord (Mm7) is…', c: 'A major triad plus a minor 7th', w: ['A major triad plus a major 7th', 'A minor triad plus a minor 7th', 'A diminished triad plus a 7th'] },
    { p: 'A half-diminished seventh (ø7) is…', c: 'A diminished triad plus a minor 7th', w: ['A diminished triad plus a diminished 7th', 'A minor triad plus a minor 7th', 'A major triad plus a minor 7th'] },
    { p: 'A fully diminished seventh (°7) stacks only…', c: 'Minor 3rds', w: ['Major 3rds', 'Perfect 4ths', 'Whole steps'] },
    { p: 'The figured-bass symbol for a first-inversion triad is…', c: '6', w: ['6/4', '7', '5/3'] },
    { p: 'The figured-bass symbol for a second-inversion triad is…', c: '6/4', w: ['6', '4/2', '6/5'] },
    { p: 'A first-inversion seventh chord is figured…', c: '6/5', w: ['4/3', '4/2', '7'] },
    { p: 'In first inversion, which chord member is in the bass?', c: 'The third', w: ['The root', 'The fifth', 'The seventh'] },
    { p: 'The lead-sheet symbol "Cm7" means…', c: 'C minor triad plus a minor 7th', w: ['C major triad plus a major 7th', 'C diminished 7th', 'C major add 7'] },
  ],
  '3.5': [
    { p: 'In major, the triad built on scale degree 5 is…', c: 'Major (V)', w: ['Minor (v)', 'Diminished (v°)', 'Augmented (V+)'] },
    { p: 'In major, the triad built on scale degree 2 is…', c: 'Minor (ii)', w: ['Major (II)', 'Diminished (ii°)', 'Augmented'] },
    { p: 'In major, the triad built on scale degree 7 is…', c: 'Diminished (vii°)', w: ['Major (VII)', 'Minor (vii)', 'Augmented'] },
    { p: 'The standard functional progression is…', c: 'Tonic → Predominant → Dominant → Tonic', w: ['Dominant → Tonic → Predominant', 'Tonic → Dominant → Predominant', 'Predominant → Tonic → Dominant'] },
    { p: 'Which chords have predominant function?', c: 'ii and IV', w: ['I and vi', 'V and vii°', 'iii and I'] },
    { p: 'A V–I cadence with both chords in root position and tonic in the soprano is a…', c: 'Perfect authentic cadence', w: ['Imperfect authentic cadence', 'Half cadence', 'Plagal cadence'] },
    { p: 'A phrase ending on V is a…', c: 'Half cadence', w: ['Authentic cadence', 'Plagal cadence', 'Deceptive cadence'] },
    { p: 'V resolving to vi instead of I is a…', c: 'Deceptive cadence', w: ['Half cadence', 'Plagal cadence', 'Authentic cadence'] },
    { p: 'The IV–I "Amen" cadence is called…', c: 'Plagal', w: ['Authentic', 'Half', 'Deceptive'] },
  ],
  '3.6': [
    { p: 'SATB order from highest to lowest voice is…', c: 'Soprano, Alto, Tenor, Bass', w: ['Soprano, Tenor, Alto, Bass', 'Alto, Soprano, Bass, Tenor', 'Bass, Tenor, Alto, Soprano'] },
    { p: 'Two voices moving in the same direction by the same interval show ______ motion.', c: 'Parallel', w: ['Similar', 'Contrary', 'Oblique'] },
    { p: 'Two voices moving in opposite directions show ______ motion.', c: 'Contrary', w: ['Parallel', 'Oblique', 'Similar'] },
    { p: 'One voice holds while the other moves: ______ motion.', c: 'Oblique', w: ['Parallel', 'Contrary', 'Similar'] },
    { p: 'Which parallels are forbidden in common-practice part writing?', c: 'Parallel 5ths and octaves', w: ['Parallel 3rds and 6ths', 'Parallel 4ths only', 'All parallel motion'] },
    { p: 'The leading tone in an outer voice should resolve…', c: 'Up by step to the tonic', w: ['Down by step', 'Down a third', 'Anywhere'] },
    { p: 'The chordal 7th should resolve…', c: 'Down by step', w: ['Up by step', 'Up a third', 'It stays'] },
    { p: 'In a root-position major triad (SATB), the best note to double is the…', c: 'Root', w: ['Third', 'Fifth', 'Seventh'] },
  ],
  '3.7': [
    { p: 'A non-chord tone approached and left by step in the same direction is a…', c: 'Passing tone', w: ['Neighbor tone', 'Suspension', 'Anticipation'] },
    { p: 'A non-chord tone that steps away and returns to the same note is a…', c: 'Neighbor tone', w: ['Passing tone', 'Escape tone', 'Pedal point'] },
    { p: 'A suspension follows the pattern…', c: 'Preparation, suspension, resolution down', w: ['Leap up, step down', 'Step up, leap down', 'Hold, leap, hold'] },
    { p: 'A retardation is like a suspension but resolves…', c: 'Up', w: ['Down', 'By leap', 'Never'] },
    { p: 'A non-chord tone approached by leap and resolved by step is an…', c: 'Appoggiatura', w: ['Anticipation', 'Passing tone', 'Pedal point'] },
    { p: 'A note that arrives early, before its chord, is an…', c: 'Anticipation', w: ['Appoggiatura', 'Suspension', 'Escape tone'] },
    { p: 'A sustained bass note held while harmonies change above it is a…', c: 'Pedal point', w: ['Suspension', 'Passing tone', 'Drone tone error'] },
    { p: 'A 4–3 suspension resolves to which chord member?', c: 'The third', w: ['The root', 'The fifth', 'The seventh'] },
  ],
  '3.8': [
    { p: 'V/V ("five of five") in C major is…', c: 'D major', w: ['G major', 'A major', 'F major'], e: 'The dominant of G (which is V in C).' },
    { p: 'A secondary dominant temporarily treats a diatonic chord as…', c: 'A new tonic', w: ['A passing chord', 'A pedal', 'A suspension'] },
    { p: 'A brief emphasis of a non-tonic chord without changing key is…', c: 'Tonicization', w: ['Modulation', 'Transposition', 'Inversion'] },
    { p: 'A full, lasting change of key is…', c: 'Modulation', w: ['Tonicization', 'Sequence', 'Cadence'] },
    { p: 'Closely related keys differ by how many accidentals?', c: 'At most one', w: ['Exactly two', 'Three or more', 'None'] },
    { p: 'A pivot chord must be diatonic in…', c: 'Both the old and new keys', w: ['Only the old key', 'Only the new key', 'Neither key'] },
    { p: 'The most common modulation from a major key is to…', c: 'The dominant (V)', w: ['The subdominant', 'The parallel minor', 'The Neapolitan'] },
  ],
  '3.9': [
    { p: 'Which meters are compound?', c: '6/8, 9/8, 12/8', w: ['2/4, 3/4, 4/4', '5/4, 7/8', '2/2, 3/2'] },
    { p: '5/4 and 7/8 are examples of ______ meters.', c: 'Asymmetric', w: ['Compound', 'Simple', 'Cut'] },
    { p: 'A triplet fits three notes into the time of…', c: 'Two of the same value', w: ['Three of the same value', 'Four of the same value', 'One beat always'] },
    { p: 'A duplet (in compound meter) fits two notes into the time of…', c: 'Three', w: ['Two', 'Four', 'Six'] },
    { p: 'Accenting normally weak beats or offbeats is…', c: 'Syncopation', w: ['Hemiola', 'Rubato', 'Anacrusis'] },
    { p: 'Hemiola is the feel of…', c: 'Three against two', w: ['Four against three', 'Two against two', 'Free rhythm'] },
    { p: 'In 6/8 at a quick tempo, the conductor usually beats…', c: '2', w: ['6', '3', '4'] },
  ],
  '3.10': [
    { p: 'A musical phrase most often lasts…', c: '4 measures', w: ['1 measure', '2 beats', '16 measures'] },
    { p: 'Two phrases in an antecedent–consequent pair form a…', c: 'Period', w: ['Sentence', 'Motive', 'Coda'] },
    { p: 'A sentence structure is typically…', c: 'Idea, repeated idea, continuation (1+1+2)', w: ['Two equal phrases', 'Three identical phrases', 'A free fantasy'] },
    { p: 'Binary form is…', c: 'AB', w: ['ABA', 'AAA', 'ABACA'] },
    { p: 'Ternary form is…', c: 'ABA', w: ['AB', 'AABB', 'ABCD'] },
    { p: 'Rounded binary brings back…', c: 'The opening material at the end of the B section', w: ['A new theme', 'The B section twice', 'Only the cadence'] },
    { p: 'The 12-bar blues progression uses which chords?', c: 'I, IV, V', w: ['ii, V, I', 'I, vi, iii', 'IV, V, vi only'] },
    { p: 'Theme and variations keeps which element most recognizable?', c: 'The theme\u2019s underlying structure', w: ['The exact melody every time', 'The same dynamics', 'The same key only'] },
  ],
  '3.11': [
    { p: 'In melodic dictation, the best first step is to capture the…', c: 'Rhythm and contour', w: ['Exact dynamics', 'Chord symbols', 'Tempo marking'] },
    { p: 'In harmonic dictation, listen first to which voice?', c: 'The bass', w: ['The soprano', 'The alto', 'The tenor'] },
    { p: 'Hearing "do–mi–sol" outlines which chord?', c: 'The tonic triad', w: ['The dominant', 'The subdominant', 'A seventh chord'] },
    { p: 'A melody ending sol→do gives a feeling of…', c: 'Resolution (authentic close)', w: ['Suspense', 'A half cadence', 'Modulation'] },
    { p: 'Movable-do solfège assigns "do" to…', c: 'The tonic of the current key', w: ['Always C', 'The lowest note', 'The first note of the piece'] },
    { p: 'Error detection asks you to compare…', c: 'The notation against what is performed', w: ['Two scores', 'Two performers', 'Dynamics only'] },
  ],

  // ─── Level 4: College ───
  '4.1': [
    { p: 'A cadential 6/4 resolves to…', c: 'V (the dominant)', w: ['I', 'IV', 'vi'], e: 'It decorates V: 6/4 → 5/3 over the dominant bass.' },
    { p: 'A passing 6/4 typically harmonizes…', c: 'A passing tone in the bass', w: ['A pedal bass', 'A cadence', 'A modulation'] },
    { p: 'A pedal 6/4 keeps which note stationary?', c: 'The bass', w: ['The soprano', 'The third', 'The seventh'] },
    { p: 'A descending-fifths sequence moves roots…', c: 'Down a 5th (or up a 4th) each step', w: ['Up a 5th each step', 'Down a 3rd each step', 'Chromatically'] },
    { p: 'In a 5–6 sequence, the intervals above the bass alternate…', c: '5ths and 6ths', w: ['3rds and 4ths', 'Octaves and 5ths', '6ths and 7ths'] },
    { p: 'The arpeggiated 6/4 results from…', c: 'The bass arpeggiating chord tones', w: ['A suspension', 'A passing tone', 'Mode mixture'] },
  ],
  '4.2': [
    { p: 'Mode mixture borrows chords from…', c: 'The parallel key', w: ['The relative key', 'The dominant key', 'Any remote key'] },
    { p: 'The Neapolitan chord is built on…', c: 'The lowered 2nd scale degree', w: ['The raised 4th', 'The lowered 6th', 'The 7th'] },
    { p: 'The Neapolitan usually appears in…', c: 'First inversion (N6)', w: ['Root position', 'Second inversion', 'Fourth inversion'] },
    { p: 'All augmented sixth chords contain the interval of an augmented 6th that resolves…', c: 'Outward to an octave', w: ['Inward to a third', 'To a unison', 'Down a fifth'] },
    { p: 'The German +6 differs from the Italian +6 by adding…', c: 'A perfect 5th above the bass', w: ['An augmented 4th', 'A major 2nd', 'A 7th'] },
    { p: 'The French +6 contains which distinctive interval above the bass?', c: 'An augmented 4th', w: ['A perfect 5th', 'A minor 7th', 'A diminished 3rd'] },
    { p: 'Augmented sixth chords function as…', c: 'Predominants resolving to V', w: ['Tonics', 'Dominant substitutes for I', 'Passing 6/4s'] },
    { p: 'A borrowed iv chord in a major key lowers which note?', c: 'The 6th scale degree', w: ['The 3rd', 'The 2nd', 'The 7th'] },
  ],
  '4.3': [
    { p: 'A °7 chord is enharmonically reusable because it…', c: 'Divides the octave equally, so any note can be the root', w: ['Has no third', 'Contains only perfect intervals', 'Is always in root position'] },
    { p: 'The German +6 is enharmonically equivalent to…', c: 'A dominant seventh chord', w: ['A half-diminished seventh', 'A major seventh', 'A minor triad'] },
    { p: 'Chromatic mediants share how many common tones (typically)?', c: 'One (or none)', w: ['Three', 'All four', 'Always two'] },
    { p: 'C major to E major is an example of…', c: 'A chromatic mediant relationship', w: ['A diatonic mediant', 'A dominant relation', 'Mode mixture'] },
    { p: 'A common-tone diminished seventh resolves to a chord that shares…', c: 'One of its tones', w: ['Its bass', 'No tones', 'All its tones'] },
    { p: 'A dominant 13th chord stacks how many different pitches in full?', c: '7', w: ['5', '6', '13'] },
    { p: 'Distant modulation often travels through…', c: 'Enharmonic reinterpretation of °7 or Ger+6', w: ['Only pivot triads', 'Silence', 'Parallel octaves'] },
  ],
  '4.4': [
    { p: 'First species counterpoint is…', c: 'Note against note', w: ['Two notes against one', 'Four against one', 'Free rhythm'] },
    { p: 'Second species counterpoint sets…', c: 'Two notes against one', w: ['One against one', 'Syncopated ties', 'Florid mixture'] },
    { p: 'Fourth species counterpoint features…', c: 'Suspensions (syncopation)', w: ['Note against note', 'Triplets', 'Parallel 5ths'] },
    { p: 'In strict counterpoint, you should approach a perfect consonance by…', c: 'Contrary or oblique motion', w: ['Parallel motion', 'Similar motion always', 'Leap in both voices'] },
    { p: 'In a fugue, the opening statement of the theme is the…', c: 'Subject', w: ['Answer', 'Episode', 'Stretto'] },
    { p: 'A fugue answer at the dominant with intervals adjusted to stay in key is a…', c: 'Tonal answer', w: ['Real answer', 'False answer', 'Inverted answer'] },
    { p: 'Overlapping subject entries before the previous finishes is…', c: 'Stretto', w: ['Episode', 'Exposition', 'Augmentation'] },
    { p: 'A passage in a fugue without a full subject statement is an…', c: 'Episode', w: ['Exposition', 'Answer', 'Anacrusis'] },
    { p: 'A canon at the octave means the follower…', c: 'Imitates exactly, an octave away', w: ['Inverts the melody', 'Plays it backwards', 'Doubles the leader'] },
  ],
  '4.5': [
    { p: 'Sonata form\u2019s three main sections are…', c: 'Exposition, development, recapitulation', w: ['Verse, chorus, bridge', 'A, B, A', 'Intro, theme, coda'] },
    { p: 'In a major-key exposition, the second theme is usually in…', c: 'The dominant', w: ['The tonic', 'The relative minor', 'The subdominant'] },
    { p: 'In the recapitulation, the second theme returns in…', c: 'The tonic', w: ['The dominant', 'The relative major', 'A new key'] },
    { p: 'A rondo alternates a refrain with…', c: 'Contrasting episodes (ABACA)', w: ['Exact repeats (AAAA)', 'One single trio', 'A fugue'] },
    { p: 'Ritornello form is most associated with…', c: 'The Baroque concerto', w: ['The art song', 'The 12-bar blues', 'Gregorian chant'] },
    { p: 'In strophic song form, each verse is sung to…', c: 'The same music', w: ['New music', 'Inverted music', 'A different key'] },
    { p: 'Through-composed song form means…', c: 'Continuously new music, no repeated strophes', w: ['One repeated strophe', 'ABA', 'Refrain plus episodes'] },
  ],
  '4.6': [
    { p: 'Normal form of a pitch-class set is…', c: 'Its most compact ascending ordering', w: ['Its prime transposition', 'Any ascending order', 'Lowest note first'] },
    { p: 'A twelve-tone row contains…', c: 'All 12 pitch classes exactly once', w: ['12 random notes', 'A 12-note melody in a key', 'Only chromatic steps'] },
    { p: 'The four basic row forms are…', c: 'Prime, inversion, retrograde, retrograde-inversion', w: ['Tonic, dominant, subdominant, leading', 'Major, minor, dim, aug', 'P, Q, R, S'] },
    { p: 'The retrograde of a row states it…', c: 'Backwards', w: ['Upside down', 'Transposed', 'In doubled rhythm'] },
    { p: 'The octatonic scale alternates…', c: 'Half and whole steps', w: ['Whole steps only', 'Half steps only', 'Thirds'] },
    { p: 'Messiaen\u2019s "modes of limited transposition" are special because they…', c: 'Map onto themselves after few transpositions', w: ['Use quarter tones', 'Have no tonic', 'Are always seven notes'] },
    { p: 'Centricity without functional harmony means…', c: 'A pitch is emphasized without dominant–tonic function', w: ['There is no central pitch', 'Traditional cadences define the center', 'Only drones are used'] },
    { p: 'Minimalism is characterized by…', c: 'Repetition and gradual process', w: ['Dense atonal counterpoint', 'Strict sonata form', 'Improvised cadenzas'] },
  ],
  '4.7': [
    { p: 'The ii–V–I in C major is…', c: 'Dm7 – G7 – Cmaj7', w: ['Cm7 – F7 – B♭maj7', 'Em7 – A7 – Dmaj7', 'Dm7 – A7 – Gmaj7'] },
    { p: 'Tritone substitution replaces G7 with…', c: 'D♭7', w: ['B7', 'E7', 'A♭maj7'], e: 'They share the same tritone (B/F = C♭/F).' },
    { p: 'In a C7(♭9) chord, the ♭9 is…', c: 'D♭', w: ['D', 'E♭', 'A♭'] },
    { p: 'Chord-scale theory pairs a dominant 7th chord most basically with…', c: 'Mixolydian', w: ['Ionian', 'Dorian', 'Locrian'] },
    { p: 'A "♯11" on a major chord suggests which mode?', c: 'Lydian', w: ['Mixolydian', 'Phrygian', 'Aeolian'] },
    { p: 'Modal interchange in pop/gospel commonly borrows ♭VII from…', c: 'The parallel minor (or Mixolydian)', w: ['The dominant key', 'The relative minor', 'Lydian'] },
    { p: 'A passing diminished chord in gospel often connects…', c: 'Two diatonic chords a whole step apart', w: ['Tonic and dominant a 5th apart', 'Two identical chords', 'Remote keys only'] },
    { p: 'A turnaround\u2019s job is to…', c: 'Lead back to the top of the form', w: ['End the piece', 'Change meter', 'Modulate permanently'] },
  ],
  '4.8': [
    { p: 'A B♭ clarinet sounding a written C produces…', c: 'B♭', w: ['C', 'D', 'A'], e: 'B♭ instruments sound a major 2nd below written pitch.' },
    { p: 'To write a concert-pitch melody for a B♭ instrument, transpose it…', c: 'Up a major 2nd', w: ['Down a major 2nd', 'Up a minor 3rd', 'Not at all'] },
    { p: 'An F horn sounding a written C produces…', c: 'F a perfect 5th below', w: ['F a 4th above', 'C', 'B♭ a 2nd below'] },
    { p: 'An E♭ alto saxophone sounds…', c: 'A major 6th below written pitch', w: ['A major 2nd below', 'A perfect 5th below', 'At written pitch'] },
    { p: 'The alto clef centers middle C on…', c: 'The middle (3rd) line', w: ['The 4th line', 'The bottom line', 'The 3rd space'] },
    { p: 'The tenor clef centers middle C on…', c: 'The 4th line', w: ['The 3rd line', 'The top line', 'The 2nd space'] },
    { p: 'Which instrument commonly reads tenor clef in its upper register?', c: 'Cello', w: ['Violin', 'Flute', 'Tuba'] },
    { p: 'Open score means…', c: 'Each voice on its own staff', w: ['Two voices per staff', 'No bar lines', 'Unmeasured notation'] },
  ],
  '4.9': [
    { p: 'In Schenkerian analysis, the Urlinie is…', c: 'The fundamental descending upper-voice line', w: ['The bass arpeggiation', 'The opening motive', 'A 12-tone row'] },
    { p: 'Prolongation means…', c: 'A harmony remains in control while other chords elaborate it', w: ['Holding a fermata', 'Playing slower', 'Repeating the exposition'] },
    { p: 'The fundamental bass motion in Schenker\u2019s Ursatz is…', c: 'I–V–I', w: ['I–IV–I', 'ii–V–I', 'I–vi–IV–V'] },
    { p: 'Schenker\u2019s three structural levels are…', c: 'Foreground, middleground, background', w: ['Soprano, alto, bass', 'Phrase, period, sentence', 'Motive, theme, form'] },
    { p: 'A reduction removes…', c: 'Surface embellishment to show structure', w: ['The bass line', 'All harmony', 'The form'] },
  ],
  '4.10': [
    { p: 'In atonal interval identification, interval class 6 is the…', c: 'Tritone', w: ['Perfect 5th', 'Minor 2nd', 'Major 3rd'] },
    { p: 'Interval class counts the distance between pitch classes as…', c: 'The smaller of an interval and its inversion', w: ['Always the ascending form', 'Semitones up to 12', 'Staff steps'] },
    { p: 'A trichord is…', c: 'A set of three pitch classes', w: ['Three chords', 'A triad in root position only', 'Three staves'] },
    { p: 'In four-part harmonic dictation, you notate…', c: 'Outer voices plus Roman numerals (then inner voices)', w: ['Only the melody', 'Only chord symbols', 'The alto first'] },
    { p: 'Chromatic dictation is easier when you anchor to…', c: 'Scale degrees and resolution tendencies', w: ['Absolute frequencies', 'The tempo', 'Dynamics'] },
    { p: 'Sight-singing post-tonal melodies relies most on…', c: 'Interval reading', w: ['Key signatures', 'Chord function', 'Lyrics'] },
  ],
};
