import { User } from "@/hooks/useUsers";

export const mockUsers: User[] = [
  {
    id: "mock-user-1",
    email: "sarah.johnson@example.com",
    full_name: "Sarah Johnson",
    role: "user",
    created_at: "2023-08-15T10:30:00Z",
    exec_board_role: "President",
    is_exec_board: true,
  },
  {
    id: "mock-user-2", 
    email: "michael.chen@example.com",
    full_name: "Michael Chen",
    role: "user",
    created_at: "2023-09-01T14:15:00Z",
    exec_board_role: "Vice President",
    is_exec_board: true,
  },
  {
    id: "mock-user-3",
    email: "emily.rodriguez@example.com", 
    full_name: "Emily Rodriguez",
    role: "admin",
    created_at: "2023-07-20T09:45:00Z",
    exec_board_role: "Secretary",
    is_exec_board: true,
  },
  {
    id: "mock-user-4",
    email: "james.wilson@example.com",
    full_name: "James Wilson", 
    role: "user",
    created_at: "2023-08-30T16:20:00Z",
    exec_board_role: "Treasurer",
    is_exec_board: true,
  },
  {
    id: "mock-user-5",
    email: "maria.garcia@example.com",
    full_name: "Maria Garcia",
    role: "user", 
    created_at: "2023-09-10T11:00:00Z",
    exec_board_role: "Business Manager",
    is_exec_board: true,
  },
  {
    id: "mock-user-6",
    email: "david.kim@example.com",
    full_name: "David Kim",
    role: "user",
    created_at: "2023-08-05T13:30:00Z",
    exec_board_role: null,
    is_exec_board: false,
  },
  {
    id: "mock-user-7",
    email: "ashley.brown@example.com",
    full_name: "Ashley Brown",
    role: "user",
    created_at: "2023-09-05T15:45:00Z",
    exec_board_role: "Librarian",
    is_exec_board: true,
  },
  {
    id: "mock-user-8",
    email: "christopher.lee@example.com",
    full_name: "Christopher Lee",
    role: "user",
    created_at: "2023-08-20T12:10:00Z",
    exec_board_role: null,
    is_exec_board: false,
  },
  {
    id: "mock-user-9",
    email: "taylor.smith@example.com",
    full_name: "Taylor Smith",
    role: "user",
    created_at: "2023-09-15T10:20:00Z",
    exec_board_role: "Chaplain",
    is_exec_board: true,
  },
  {
    id: "mock-user-10",
    email: "jordan.davis@example.com",
    full_name: "Jordan Davis",
    role: "user",
    created_at: "2023-08-25T14:55:00Z",
    exec_board_role: null,
    is_exec_board: false,
  },
  {
    id: "mock-user-11",
    email: "alexis.martinez@example.com",
    full_name: "Alexis Martinez",
    role: "user",
    created_at: "2023-09-08T16:30:00Z",
    exec_board_role: "Historian",
    is_exec_board: true,
  },
  {
    id: "mock-user-12",
    email: "cameron.thompson@example.com",
    full_name: "Cameron Thompson",
    role: "user",
    created_at: "2023-08-12T11:40:00Z",
    exec_board_role: null,
    is_exec_board: false,
  },
  {
    id: "mock-user-13",
    email: "riley.anderson@example.com",
    full_name: "Riley Anderson",
    role: "user",
    created_at: "2023-09-03T09:15:00Z",
    exec_board_role: "Social Chair",
    is_exec_board: true,
  },
  {
    id: "mock-user-14",
    email: "morgan.white@example.com",
    full_name: "Morgan White",
    role: "user",
    created_at: "2023-08-18T17:25:00Z",
    exec_board_role: null,
    is_exec_board: false,
  },
  {
    id: "mock-user-15",
    email: "avery.jackson@example.com",
    full_name: "Avery Jackson",
    role: "user",
    created_at: "2023-09-12T13:50:00Z",
    exec_board_role: null,
    is_exec_board: false,
  }
];