/**
 * Shared SQL emission helpers for the Prayer import scripts.
 *
 * The importers write idempotent SQL to a file rather than writing to the
 * database directly. That matches how production DB changes are applied here
 * (reviewed, then run by hand), keeps the scripts dependency-free — no pg or
 * supabase-js needed — and means the exact statements can be read before they
 * touch anything.
 */

/** Quotes a value as a SQL literal. Nulls and undefined become NULL. */
export function lit(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  return `'${value.replace(/'/g, "''")}'`;
}

/** Quotes a string array as a SQL text[] literal. */
export function arrayLit(values: string[]): string {
  if (!values.length) return `'{}'`;
  return `ARRAY[${values.map((v) => lit(v)).join(',')}]::text[]`;
}

/** Header every generated file carries, so an unlabelled file is never a mystery. */
export function header(title: string, source: string, rows: number): string {
  return [
    `-- ${title}`,
    `-- Generated by a Prayer module import script. Do not edit by hand.`,
    `-- Source: ${source}`,
    `-- Rows: ${rows}`,
    `--`,
    `-- Idempotent: re-running updates existing rows rather than duplicating.`,
    `BEGIN;`,
    '',
  ].join('\n');
}

export const FOOTER = '\nCOMMIT;\n';
