#!/usr/bin/env python3
"""Generate SQL that loads GSA Auctions medical lots into the Auctions module.

GSA is the ONE source in this module with a sanctioned automated path: an
official public API, a free self-serve key from api.data.gov, and no
anti-automation clause in their terms. Every other tracked house forbids
crawling (see ext_auction_sources.notes) and must arrive by email or by hand.

The endpoint is a whole-dataset dump with no query parameters, so we pull it
all and filter locally.

    python3 scripts/pull-gsa-auctions.py > /tmp/gsa.sql
    ssh root@198.211.113.144 "docker exec -i supabase-db psql -U supabase_admin \
      -d postgres -v ON_ERROR_STOP=1" < /tmp/gsa.sql

Re-running is safe: auctions upsert on (source_id, external_id) and lots do
nothing on conflict.

Set GSA_API_KEY for real use; DEMO_KEY works for a look but is rate-limited.
"""
import html
import json
import os
import re
import sys
import urllib.request
from collections import OrderedDict

API = "https://api.gsa.gov/assets/gsaauctions/v2/auctions?api_key="

# Matched against itemName ONLY. Searching the whole record matches 725 of 781
# lots — including a 1978 Beechcraft — because words like "lab" appear in
# agency and address fields.
MEDICAL = re.compile(
    r"\b(mri|ct scan|c-arm|ultrasound|x-ray|xray|radiolog|imaging|analyzer|"
    r"centrifuge|medical|hospital|surgical|patient|defibrillat|exam table|"
    r"autoclave|endoscop|microscope|sterili)\b",
    re.I,
)


def q(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def strip_html(raw):
    if not raw:
        return None
    t = re.sub(r"<(script|style)[^>]*>.*?</\1>", "", raw, flags=re.S | re.I)
    t = re.sub(r"<br\s*/?>|</(p|li|h[1-6]|ul|div)>", "\n", t, flags=re.I)
    t = re.sub(r"<[^>]+>", " ", t)
    t = html.unescape(t)
    t = re.sub(r"[ \t]+", " ", t)
    t = re.sub(r" *\n *", "\n", t)
    return re.sub(r"\n{3,}", "\n\n", t).strip() or None


def ts(d):
    # GSA publishes DATES with no clock time. Stored at 12:00Z so the calendar
    # shows the right day in every US timezone instead of slipping back one.
    return f"'{d}T12:00:00Z'" if d else "NULL"


def main():
    key = os.environ.get("GSA_API_KEY", "DEMO_KEY")
    with urllib.request.urlopen(API + key, timeout=120) as r:
        data = json.load(r)
    recs = data if isinstance(data, list) else next(
        (v for v in data.values() if isinstance(v, list)), [])
    hits = [x for x in recs if MEDICAL.search(str(x.get("itemName", "")))]

    sales = OrderedDict()
    for r in hits:
        sales.setdefault(str(r.get("saleNo")), []).append(r)

    print(f"-- GSA Auctions medical lots — generated by scripts/pull-gsa-auctions.py")
    print(f"-- {len(recs)} lots in the feed, {len(hits)} medical by item name, {len(sales)} sales.")
    print("BEGIN;\n")
    for sale_no, lots in sales.items():
        places = {(l.get("propertyCity") or "").strip(): (l.get("propertyState") or "").strip()
                  for l in lots}
        cities = sorted(c for c in places if c)
        states = sorted({s for s in places.values() if s})
        if len(cities) == 1 and len(states) == 1:
            city = " ".join(w.capitalize() for w in cities[0].split())
            state = states[0]
            title = f"GSA surplus — {city}, {state}"
        else:
            city, state = None, (states[0] if len(states) == 1 else None)
            title = f"GSA surplus — {len(cities)} locations"
        opens = min(l.get("aucStartDt") for l in lots)
        closes = max(l.get("aucEndDt") for l in lots)
        status = "announced" if all(
            (l.get("auctionStatus") or "") == "Preview" for l in lots) else "open"

        print(f"-- sale {sale_no}: {len(lots)} medical lot(s)")
        print(f"""INSERT INTO ext_auctions (source_id, external_id, title, location_city, location_state, opens_at, closes_at, status)
SELECT s.id, {q(sale_no)}, {q(title)}, {q(city)}, {q(state)}, {ts(opens)}, {ts(closes)}, {q(status)}
FROM ext_auction_sources s WHERE s.slug='gsa-auctions'
ON CONFLICT (source_id, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET title=EXCLUDED.title, location_city=EXCLUDED.location_city,
  location_state=EXCLUDED.location_state, opens_at=EXCLUDED.opens_at,
  closes_at=EXCLUDED.closes_at, status=EXCLUDED.status;""")
        for l in lots:
            bid = l.get("highBidAmount")
            cents = "NULL" if bid in (None, "") else str(int(round(float(bid) * 100)))
            print(f"""INSERT INTO ext_auction_lots (auction_id, lot_number, raw_title, raw_text, url, current_bid_cents, closes_at)
SELECT a.id, {q(l.get('lotNo'))}, {q(l.get('itemName'))}, {q(strip_html(l.get('lotInfo')))}, {q(l.get('itemDescURL'))}, {cents}, {ts(l.get('aucEndDt'))}
FROM ext_auctions a JOIN ext_auction_sources s ON s.id=a.source_id
WHERE s.slug='gsa-auctions' AND a.external_id={q(sale_no)}
ON CONFLICT (auction_id, lot_number) WHERE lot_number IS NOT NULL DO NOTHING;""")
        print()
    print("UPDATE ext_auction_sources SET last_refreshed_at=now() WHERE slug='gsa-auctions';")
    print("COMMIT;")
    print("\n-- Lots land with review_status 'pending' (invisible to members) until")
    print("-- auctions-normalize reads their specs. Run it after loading.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
