-- Populate Auditions Management with valid data
-- First, clear any existing session data
DELETE FROM audition_applications WHERE email LIKE '%students.spelman.edu';
DELETE FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions';

-- Create a simplified audition session
INSERT INTO audition_sessions (
  name,
  description,
  start_date,
  end_date,
  application_deadline,
  is_active,
  max_applicants,
  requirements,
  created_at,
  updated_at
) VALUES (
  'Spring 2025 New Member Auditions',
  'Spring semester auditions for prospective Spelman College Glee Club members',
  CURRENT_DATE + INTERVAL '1 week',
  CURRENT_DATE + INTERVAL '3 weeks',
  CURRENT_DATE + INTERVAL '5 days',
  true,
  75,
  'Prepare one song of your choice (any genre). Basic vocal exercises and sight reading.',
  NOW(),
  NOW()
);

-- Create audition applications with proper data types
INSERT INTO audition_applications (
  session_id,
  user_id,
  full_name,
  email,
  phone_number,
  audition_time_slot,
  status,
  voice_part_preference,
  sight_reading_level,
  previous_choir_experience,
  years_of_vocal_training,
  prepared_pieces,
  why_glee_club,
  vocal_goals,
  notes,
  created_at,
  updated_at
) VALUES
  -- Get session ID and create applications
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Amara Williams',
    'amara.williams@students.spelman.edu',
    '(404) 555-1001',
    CURRENT_DATE + INTERVAL '1 week 14 hours',
    'submitted',
    'Soprano',
    'Beginner',
    'High school choir - 3 years',
    2,
    '"Amazing Grace" - Traditional',
    'I want to be part of the Spelman musical legacy and grow as a vocalist.',
    'Improve my range and stage presence',
    'Strong classical background',
    NOW() - INTERVAL '2 days',
    NOW()
  ),
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Zara Johnson',
    'zara.johnson@students.spelman.edu',
    '(404) 555-1002',
    CURRENT_DATE + INTERVAL '1 week 14 hours 15 minutes',
    'submitted',
    'Alto',
    'Intermediate',
    'Church choir since age 8',
    4,
    '"His Eye is on the Sparrow" - Gospel',
    'The Glee Club represents excellence and sisterhood in music.',
    'Learn advanced vocal techniques and harmonies',
    'Transfer student with strong musical foundation',
    NOW() - INTERVAL '1 day',
    NOW()
  ),
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Kira Thompson',
    'kira.thompson@students.spelman.edu',
    '(404) 555-1003',
    CURRENT_DATE + INTERVAL '1 week 14 hours 30 minutes',
    'submitted',
    'Soprano',
    'Advanced',
    'High school and college choir experience',
    6,
    '"O Holy Night" - Classical',
    'To challenge myself musically and be part of this historic tradition.',
    'Perfect my coloratura technique',
    'Music major with operatic training',
    NOW() - INTERVAL '3 hours',
    NOW()
  ),
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Maya Davis',
    'maya.davis@students.spelman.edu',
    '(404) 555-1004',
    CURRENT_DATE + INTERVAL '1 week 14 hours 45 minutes',
    'submitted',
    'Alto',
    'Beginner',
    'Church youth choir',
    1,
    '"Lift Every Voice and Sing"',
    'Spelman Glee Club is a dream of mine since high school.',
    'Develop my voice and gain confidence performing',
    'Strong alto voice, needs technical training',
    NOW() - INTERVAL '6 hours',
    NOW()
  ),
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Taylor Brooks',
    'taylor.brooks@students.spelman.edu',
    '(404) 555-1011',
    CURRENT_DATE + INTERVAL '1 week 2 days 14 hours',
    'callback_scheduled',
    'Soprano',
    'Advanced',
    'Regional honor choir',
    4,
    '"O mio babbino caro" - Puccini',
    'Classical music is my passion and Glee Club is the pinnacle.',
    'Prepare for graduate vocal performance programs',
    'Exceptional voice, callback for leadership potential',
    NOW() - INTERVAL '5 days',
    NOW()
  ),
  (
    (SELECT id FROM audition_sessions WHERE name = 'Spring 2025 New Member Auditions'),
    gen_random_uuid(),
    'Morgan Lee',
    'morgan.lee@students.spelman.edu',
    '(404) 555-1012',
    CURRENT_DATE + INTERVAL '1 week 2 days 14 hours 30 minutes',
    'callback_scheduled',
    'Alto',
    'Advanced',
    'State honor choir and a cappella group',
    5,
    '"The Way You Look Tonight" - Jazz Standard',
    'I love the versatility and excellence of the Glee Club repertoire.',
    'Leadership experience and advanced ensemble skills',
    'Strong leader, excellent for section leadership',
    NOW() - INTERVAL '6 days',
    NOW()
  );