-- BOWMAN SCHOLARS MODULE MIGRATION

-- ROLES
create table if not exists user_roles_multi (
  user_id uuid references auth.users(id) on delete cascade,
  role text not null check (role in ('super_admin','admin','member','bowman_scholar')),
  primary key (user_id, role),
  created_at timestamptz default now()
);

-- SCHOLAR PROFILE
create table if not exists bowman_scholars (
  user_id uuid primary key references auth.users(id) on delete cascade,
  major text,
  grad_year int,
  bio text,
  headshot_url text,
  created_at timestamptz default now()
);

-- LITURGICAL WEEK
create table if not exists liturgical_weeks (
  id uuid primary key default gen_random_uuid(),
  week_of date not null,           -- Monday of the week
  title text not null,
  lectionary_cycle text,           -- A/B/C or I/II
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  unique(week_of)
);

-- LITURGY ASSETS (PDFs, images, links)
create table if not exists liturgy_assets (
  id uuid primary key default gen_random_uuid(),
  liturgical_week_id uuid references liturgical_weeks(id) on delete cascade,
  kind text check (kind in ('pdf','image','audio','link')),
  title text,
  storage_path text,               -- Supabase Storage path
  external_url text,               -- YouTube or library link
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

-- PLAYLISTS
create table if not exists playlists (
  id uuid primary key default gen_random_uuid(),
  liturgical_week_id uuid references liturgical_weeks(id) on delete cascade,
  title text not null,
  description text,
  public boolean default true,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists playlist_items (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid references playlists(id) on delete cascade,
  position int generated by default as identity,
  source text check (source in ('youtube','glee_library','external')),
  title text not null,
  external_url text,               -- canonical URL if external
  library_track_id uuid,           -- FK to existing library table if present
  notes text,
  created_at timestamptz default now()
);

-- HELPERS
create or replace function has_role(target text)
returns boolean language sql stable as $$
  select exists(
    select 1 from user_roles_multi
    where user_id = auth.uid() and role = target
  );
$$;

create or replace function is_super_admin()
returns boolean language sql stable as $$
  select exists(
    select 1 from user_roles_multi
    where user_id = auth.uid() and role = 'super_admin'
  );
$$;

-- RLS ON
alter table user_roles_multi enable row level security;
alter table bowman_scholars  enable row level security;
alter table liturgical_weeks enable row level security;
alter table liturgy_assets    enable row level security;
alter table playlists         enable row level security;
alter table playlist_items    enable row level security;

-- RLS: user_roles_multi
drop policy if exists urm_self_read on user_roles_multi;
drop policy if exists urm_admin_all on user_roles_multi;
create policy urm_self_read on user_roles_multi
for select using (user_id = auth.uid() or is_super_admin());
create policy urm_admin_all on user_roles_multi
for all using (is_super_admin()) with check (is_super_admin());

-- RLS: bowman_scholars
drop policy if exists bs_read on bowman_scholars;
drop policy if exists bs_write_self on bowman_scholars;
drop policy if exists bs_admin on bowman_scholars;
create policy bs_read on bowman_scholars
for select using (true);
create policy bs_write_self on bowman_scholars
for insert with check (auth.uid() = user_id);
create policy bs_write_self_upd on bowman_scholars
for update using (auth.uid() = user_id);
create policy bs_admin on bowman_scholars
for all using (is_super_admin()) with check (is_super_admin());

-- RLS: liturgical_weeks
drop policy if exists lw_read_all on liturgical_weeks;
drop policy if exists lw_write_admin on liturgical_weeks;
drop policy if exists lw_insert_creator on liturgical_weeks;
drop policy if exists lw_update_creator on liturgical_weeks;
create policy lw_read_all on liturgical_weeks for select using (true);
create policy lw_write_admin on liturgical_weeks for all
  using (is_super_admin() or has_role('admin')) with check (is_super_admin() or has_role('admin'));
create policy lw_insert_creator on liturgical_weeks for insert
  with check (auth.uid() = created_by or is_super_admin() or has_role('admin'));
create policy lw_update_creator on liturgical_weeks for update
  using (auth.uid() = created_by or is_super_admin() or has_role('admin'));

-- RLS: liturgy_assets
drop policy if exists la_read on liturgy_assets;
drop policy if exists la_admin on liturgy_assets;
drop policy if exists la_ins_creator on liturgy_assets;
drop policy if exists la_upd_creator on liturgy_assets;
create policy la_read on liturgy_assets for select using (true);
create policy la_admin on liturgy_assets for all
  using (is_super_admin() or has_role('admin')) with check (is_super_admin() or has_role('admin'));
create policy la_ins_creator on liturgy_assets for insert
  with check (auth.uid() = created_by or is_super_admin() or has_role('admin'));
create policy la_upd_creator on liturgy_assets for update
  using (auth.uid() = created_by or is_super_admin() or has_role('admin'));

-- RLS: playlists
drop policy if exists pl_read on playlists;
drop policy if exists pl_admin on playlists;
drop policy if exists pl_ins_creator on playlists;
drop policy if exists pl_upd_creator on playlists;
create policy pl_read on playlists for select using (public = true or is_super_admin() or has_role('admin') or auth.uid() = created_by);
create policy pl_admin on playlists for all
  using (is_super_admin() or has_role('admin')) with check (is_super_admin() or has_role('admin'));
create policy pl_ins_creator on playlists for insert
  with check (auth.uid() = created_by or is_super_admin() or has_role('admin'));
create policy pl_upd_creator on playlists for update
  using (auth.uid() = created_by or is_super_admin() or has_role('admin'));

-- RLS: playlist_items
drop policy if exists pli_read on playlist_items;
drop policy if exists pli_admin on playlist_items;
drop policy if exists pli_ins_creator on playlist_items;
drop policy if exists pli_upd_creator on playlist_items;
create policy pli_read on playlist_items for select using (true);
create policy pli_admin on playlist_items for all
  using (is_super_admin() or has_role('admin')) with check (is_super_admin() or has_role('admin'));
create policy pli_ins_creator on playlist_items for insert
  with check (exists(select 1 from playlists p where p.id = playlist_id and (p.created_by = auth.uid() or is_super_admin() or has_role('admin'))));
create policy pli_upd_creator on playlist_items for update
  using (exists(select 1 from playlists p where p.id = playlist_id and (p.created_by = auth.uid() or is_super_admin() or has_role('admin'))));

-- Storage buckets
insert into storage.buckets (id, name, public) values
  ('bowman-liturgy-pdfs','bowman-liturgy-pdfs', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public) values
  ('bowman-images','bowman-images', true)
on conflict (id) do nothing;

-- Storage policies
create policy "public read bowman" on storage.objects
for select using (bucket_id in ('bowman-liturgy-pdfs','bowman-images'));

create policy "write bowman by creator/admin" on storage.objects
for insert with check (
  bucket_id in ('bowman-liturgy-pdfs','bowman-images') and (auth.role() = 'authenticated')
);

create policy "update bowman by owner/admin" on storage.objects
for update using (
  bucket_id in ('bowman-liturgy-pdfs','bowman-images') and (auth.uid() = owner or is_super_admin() or has_role('admin'))
) with check (true);