-- BOWMAN SCHOLARS MODULE MIGRATION (Corrected)

-- ROLES
create table if not exists user_roles_multi (
  user_id uuid references auth.users(id) on delete cascade,
  role text not null check (role in ('super_admin','admin','member','bowman_scholar')),
  primary key (user_id, role),
  created_at timestamptz default now()
);

-- SCHOLAR PROFILE
create table if not exists bowman_scholars (
  user_id uuid primary key references auth.users(id) on delete cascade,
  major text,
  grad_year int,
  bio text,
  headshot_url text,
  created_at timestamptz default now()
);

-- LITURGICAL WEEK
create table if not exists liturgical_weeks (
  id uuid primary key default gen_random_uuid(),
  week_of date not null,           -- Monday of the week
  title text not null,
  lectionary_cycle text,           -- A/B/C or I/II
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  unique(week_of)
);

-- LITURGY ASSETS (PDFs, images, links)
create table if not exists liturgy_assets (
  id uuid primary key default gen_random_uuid(),
  liturgical_week_id uuid references liturgical_weeks(id) on delete cascade,
  kind text check (kind in ('pdf','image','audio','link')),
  title text,
  storage_path text,               -- Supabase Storage path
  external_url text,               -- YouTube or library link
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

-- PLAYLISTS (corrected column name)
create table if not exists playlists (
  id uuid primary key default gen_random_uuid(),
  liturgical_week_id uuid references liturgical_weeks(id) on delete cascade,
  title text not null,
  description text,
  is_public boolean default true,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists playlist_items (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid references playlists(id) on delete cascade,
  position int generated by default as identity,
  source text check (source in ('youtube','glee_library','external')),
  title text not null,
  external_url text,               -- canonical URL if external
  library_track_id uuid,           -- FK to existing library table if present
  notes text,
  created_at timestamptz default now()
);

-- HELPERS
create or replace function has_role(target text)
returns boolean language sql stable as $$
  select exists(
    select 1 from user_roles_multi
    where user_id = auth.uid() and role = target
  );
$$;

create or replace function is_super_admin()
returns boolean language sql stable as $$
  select exists(
    select 1 from user_roles_multi
    where user_id = auth.uid() and role = 'super_admin'
  );
$$;

-- RLS ON
alter table user_roles_multi enable row level security;
alter table bowman_scholars  enable row level security;
alter table liturgical_weeks enable row level security;
alter table liturgy_assets    enable row level security;
alter table playlists         enable row level security;
alter table playlist_items    enable row level security;

-- Storage buckets
insert into storage.buckets (id, name, public) values
  ('bowman-liturgy-pdfs','bowman-liturgy-pdfs', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public) values
  ('bowman-images','bowman-images', true)
on conflict (id) do nothing;