-- Seed glee_academy_courses with existing course data
INSERT INTO public.glee_academy_courses (id, course_code, title, description, level, duration, highlights, icon_name, route, instructor_name, instructor_email, instructor_office, instructor_office_hours, is_active, display_order)
VALUES 
  ('a0000000-0000-0000-0000-000000000070', 'MUS 070', 'Glee Club', 'The premier choral ensemble of Spelman College with over 100 years of musical excellence.', 'Audition Required', 'Semester', ARRAY['Choral Performance', 'Vocal Training', 'Tours & Concerts', 'Community'], 'Users', '/academy/mus-070', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 1),
  ('a0000000-0000-0000-0000-000000000210', 'MUS 210', 'Choral Conducting and Literature', 'Master the art of choral conducting with technique, score analysis, and repertoire selection.', 'Intermediate', '16 Weeks', ARRAY['Conducting Technique', 'Score Analysis', 'Repertoire', 'Rehearsal Skills'], 'Music', '/academy/mus-210', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 2),
  ('a0000000-0000-0000-0000-000000000240', 'MUS 240', 'Survey of African American Music', 'Explore the rich tapestry of African American musical traditions, from spirituals and blues to jazz, gospel, R&B, and hip-hop.', 'All Levels', '16 Weeks', ARRAY['Music History', 'Cultural Context', 'Listening Journals', 'Critical Analysis'], 'BookOpen', '/academy/mus-240', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 3),
  ('a0000000-0000-0000-0000-000000000101', 'MUS 101', 'Music Fundamentals Theory', 'Build a strong foundation in music theory including notation, rhythm, scales, intervals, chords, and basic harmony.', 'Beginner', '16 Weeks', ARRAY['Music Notation', 'Rhythm', 'Scales & Keys', 'Harmony Basics'], 'BookOpen', '/academy/mus-101', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 4),
  ('a0000000-0000-0000-0000-000000000001', 'MUS 001', 'Private Applied Lessons', 'One-on-one instruction in voice or instrument with personalized curriculum tailored to your skill level and musical goals.', 'All Levels', 'Ongoing', ARRAY['Individual Instruction', 'Personalized Curriculum', 'Performance Prep', 'Technique Development'], 'Mic', '/academy/mus-001', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'By Appointment', true, 5),
  ('a0000000-0000-0000-0000-000000000000', 'MUS 000', 'Sight Singing Institute', 'Intensive training in sight-reading and ear training to develop musicianship skills essential for all musicians.', 'All Levels', '8 Weeks', ARRAY['Sight Reading', 'Ear Training', 'Solfege', 'Musicianship'], 'Eye', '/academy/mus-000', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 6),
  ('a0000000-0000-0000-0000-0000000e0101', 'GLEE 101', 'Leadership Development', 'Develop leadership skills essential for executive board members and future leaders in the Glee Club organization.', 'Advanced', '16 Weeks', ARRAY['Leadership Skills', 'Team Management', 'Event Planning', 'Communication'], 'Award', '/academy/glee-101', 'Dr. Kevin Johnson', 'kjohns10@spelman.edu', 'Fine Arts 105', 'MWF 3-5 PM', true, 7)
ON CONFLICT (id) DO NOTHING;