-- Owner-role gap, part four (final): the five functions left after #564.
--
-- These gate on something OTHER than gw_profiles admin flags — app_roles,
-- course-enrollment role, or a user-id PARAMETER — so appending
-- current_user_is_admin() would also have admitted profile-level admins who
-- do not have access today. That is wider than the gap being closed, so a
-- narrow helper is introduced instead: is_tenant_owner() adds ONLY the owner.
--
-- HOW THESE BODIES WERE PRODUCED. Each function below is the exact production
-- definition read from pg_get_functiondef, with ONE anchor patched by script.
-- Nothing else is altered. The generator asserts that each anchor matches
-- exactly once and that the patch only GROWS the body, so it cannot silently
-- drop a clause. Retyping a permission expression by hand risks a slip, and a
-- slip in a permission expression is a security bug, not a typo.
--
-- Scoping per function:
--   get_roll_call_flags / _schedule    is_tenant_owner(v_uid)         session user
--   get_accessible_sheet_music         is_tenant_owner(user_id_param) parameter
--   bulk_update_user_roles_secure      is_tenant_owner(performer_id)  parameter
--   get_student_academic_record        is_tenant_owner() AND the target must be
--                                      in the current tenant, matching the
--                                      existing admin branch, so it cannot leak
--                                      another tenant's student records.
--
-- Migration already applied to production.

-- Exactly one capability: "is this user the OWNER of the tenant they are
-- currently operating in". Used by the permission functions that gate on
-- something OTHER than gw_profiles admin flags — app_roles, course enrollment
-- role, or a user-id parameter — where appending current_user_is_admin() would
-- have widened access to profile-admins as well, which is more than the owner
-- gap being closed.
--
-- Tenant-scoped by current_tenant_id(): owning tenant A confers nothing in B.
-- Takes an optional user id because several callers gate on a PARAMETER
-- (performer_id, user_id_param) rather than the session user.
--
-- No recursion: gw_tenant_members has RLS disabled and no policy on it calls
-- back into these gates.
CREATE OR REPLACE FUNCTION public.is_tenant_owner(p_user_id uuid DEFAULT NULL)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.gw_tenant_members m
    WHERE m.user_id = COALESCE(p_user_id, auth.uid())
      AND m.role = 'owner'
      AND m.tenant_id = current_tenant_id()
  );
$function$;

COMMENT ON FUNCTION public.is_tenant_owner(uuid) IS
  'True when the given user (default: the session user) owns the CURRENT '
  'tenant. Deliberately narrower than current_user_is_admin(): it adds only '
  'the owner case, without also admitting profile-level admins.';

-- Generated by patch_owner_four.py. Each body is the CURRENT production
-- definition with exactly one anchor patched; nothing else is altered.

-- get_roll_call_flags: owner clause appended
CREATE OR REPLACE FUNCTION public.get_roll_call_flags(p_session_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_session RECORD;
  v_result JSONB;
BEGIN
  SELECT * INTO v_session FROM gw_attendance_sessions WHERE id = p_session_id;
  IF v_session IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;
  IF NOT (
    EXISTS (
      SELECT 1 FROM gw_course_enrollments e
      WHERE e.course_id = v_session.course_id AND e.user_id = v_uid
        AND e.role IN ('instructor', 'ta') AND e.enrollment_status = 'enrolled'
    )
    OR EXISTS (
      SELECT 1 FROM app_roles ar
      WHERE ar.user_id = v_uid
        AND ar.role IN ('superadmin', 'admin', 'super_admin', 'super-admin')
        AND ar.is_active = true
    )
    OR public.is_tenant_owner(v_uid)
  ) THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'user_id', a.user_id,
    'student_profile_id', p.id,
    'wrong_attempts', a.wrong_attempts,
    'locked', a.wrong_attempts >= 10
  )), '[]'::jsonb) INTO v_result
  FROM (
    SELECT user_id, count(*) AS wrong_attempts
    FROM gw_attendance_challenge_attempts
    WHERE session_id = p_session_id AND was_correct = false
    GROUP BY user_id
  ) a
  LEFT JOIN gw_profiles p ON p.user_id = a.user_id;
  RETURN v_result;
END;
$function$;

-- verify: get_roll_call_flags now references is_tenant_owner
-- get_roll_call_schedule: owner clause appended
CREATE OR REPLACE FUNCTION public.get_roll_call_schedule(p_session_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_session RECORD;
  v_seed UUID;
  v_first_slot BIGINT;
  v_slots INTEGER[];
  v_tenant UUID;
BEGIN
  SELECT * INTO v_session FROM gw_attendance_sessions WHERE id = p_session_id;
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'SESSION_NOT_FOUND');
  END IF;
  IF NOT (
    EXISTS (
      SELECT 1 FROM gw_course_enrollments e
      WHERE e.course_id = v_session.course_id AND e.user_id = v_uid
        AND e.role IN ('instructor', 'ta') AND e.enrollment_status = 'enrolled'
    )
    OR EXISTS (
      SELECT 1 FROM app_roles ar
      WHERE ar.user_id = v_uid
        AND ar.role IN ('superadmin', 'admin', 'super_admin', 'super-admin')
        AND ar.is_active = true
    )
    OR public.is_tenant_owner(v_uid)
  ) THEN
    RETURN jsonb_build_object('success', false, 'error', 'NOT_AUTHORIZED');
  END IF;

  SELECT challenge_seed INTO v_seed FROM gw_attendance_session_secrets WHERE session_id = p_session_id;
  IF v_seed IS NULL THEN
    -- Session predates the trigger or was flipped to roll_call oddly; self-heal.
    v_tenant := (to_jsonb(v_session) ->> 'tenant_id')::uuid;
    INSERT INTO gw_attendance_session_secrets (session_id, tenant_id) VALUES (p_session_id, COALESCE(v_tenant, public.current_tenant_id()))
    ON CONFLICT (session_id) DO NOTHING;
    SELECT challenge_seed INTO v_seed FROM gw_attendance_session_secrets WHERE session_id = p_session_id;
  END IF;

  v_first_slot := floor(extract(epoch FROM v_session.opens_at) / 30)::bigint;
  SELECT array_agg(roll_call_symbol_for_slot(v_seed, s)) INTO v_slots
  FROM generate_series(v_first_slot, v_first_slot + 479) AS s;

  RETURN jsonb_build_object(
    'success', true,
    'first_slot', v_first_slot,
    'slots', to_jsonb(v_slots),
    'interval_seconds', 30,
    'server_now', now(),
    'closes_at', v_session.closes_at
  );
END;
$function$;

-- verify: get_roll_call_schedule now references is_tenant_owner
-- get_accessible_sheet_music: owner clause appended
CREATE OR REPLACE FUNCTION public.get_accessible_sheet_music(user_id_param uuid)
 RETURNS TABLE(id uuid, title text, composer text, pdf_url text, is_public boolean, can_access boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT 
    sm.id,
    sm.title,
    sm.composer,
    sm.pdf_url,
    sm.is_public,
    (
      sm.is_public = true 
      OR sm.created_by = user_id_param 
      OR user_can_access_sheet_music(sm.id, user_id_param)
      OR EXISTS (
        SELECT 1 FROM public.gw_profiles 
        WHERE user_id = user_id_param 
        AND (is_admin = true OR is_super_admin = true OR role IN ('member', 'admin', 'super-admin'))
      )
      OR public.is_tenant_owner(user_id_param)
    ) as can_access
  FROM public.gw_sheet_music sm
  WHERE NOT sm.is_archived
  ORDER BY sm.title;
$function$;

-- verify: get_accessible_sheet_music now references is_tenant_owner
-- get_student_academic_record: owner clause appended
CREATE OR REPLACE FUNCTION public.get_student_academic_record(p_user_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(course_id uuid, course_code text, course_title text, term text, semester text, enrolled_at timestamp with time zone, completed_at timestamp with time zone, enrollment_status text, grade text, final_percentage numeric, credit_hours integer, excused_absences integer, unexcused_absences integer, tardies integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with target as (
    select coalesce(p_user_id, auth.uid()) as user_id
  ),
  permitted as (
    select t.user_id from target t
    where t.user_id = auth.uid()
       or exists (
         select 1 from gw_profiles p
         where p.user_id = auth.uid()
           and p.tenant_id = (select tenant_id from gw_profiles where user_id = t.user_id limit 1)
           and (p.is_admin = true or p.is_super_admin = true
                or p.role in ('admin','super-admin','executive'))
       )
       or (public.is_tenant_owner()
           and (select tenant_id from gw_profiles where user_id = t.user_id limit 1)
               = current_tenant_id())
  )
  select
    c.id,
    coalesce(c.course_code, c.code),
    c.title,
    c.term,
    c.semester::text,
    e.enrolled_at,
    e.completed_at,
    e.enrollment_status::text,
    e.grade::text,
    e.final_percentage,
    e.credit_hours,
    coalesce(s.excused_rehearsal_absences, 0) + coalesce(s.excused_performance_absences, 0),
    coalesce(s.unexcused_rehearsal_absences, 0) + coalesce(s.unexcused_performance_absences, 0),
    coalesce(s.tardies, 0)
  from gw_course_enrollments e
  join gw_courses c on c.id = e.course_id
  left join gw_course_attendance_summary s on s.course_id = e.course_id and s.student_id = e.user_id
  where e.user_id in (select user_id from permitted)
  order by c.created_at desc;
$function$;

-- verify: get_student_academic_record now references is_tenant_owner
-- bulk_update_user_roles_secure: owner clause appended
CREATE OR REPLACE FUNCTION public.bulk_update_user_roles_secure(user_ids uuid[], new_role text, performer_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  updated_count integer := 0;
  current_user_profile RECORD;
  target_user_id uuid;
BEGIN
  -- Verify performer is admin
  SELECT is_admin, is_super_admin, role 
  INTO current_user_profile 
  FROM public.gw_profiles 
  WHERE user_id = performer_id;
  
  IF NOT FOUND OR NOT (
    current_user_profile.is_admin = true OR 
    current_user_profile.is_super_admin = true OR 
    current_user_profile.role IN ('admin', 'super-admin') OR
    public.is_tenant_owner(performer_id)
  ) THEN
    RAISE EXCEPTION 'Access denied: Admin privileges required';
  END IF;
  
  -- Validate new_role
  IF new_role NOT IN ('guest', 'fan', 'member', 'alumna', 'executive', 'admin', 'super-admin') THEN
    RAISE EXCEPTION 'Invalid role: %', new_role;
  END IF;
  
  -- Process each user
  FOREACH target_user_id IN ARRAY user_ids
  LOOP
    -- Prevent self-privilege escalation
    IF target_user_id = performer_id AND new_role IN ('admin', 'super-admin') THEN
      CONTINUE;
    END IF;
    
    -- Update role
    UPDATE public.gw_profiles 
    SET 
      role = new_role,
      is_admin = CASE WHEN new_role IN ('admin', 'super-admin') THEN true ELSE false END,
      is_super_admin = CASE WHEN new_role = 'super-admin' THEN true ELSE false END,
      updated_at = now()
    WHERE user_id = target_user_id;
    
    IF FOUND THEN
      updated_count := updated_count + 1;
      
      -- Log the change
      PERFORM public.log_security_event(
        'bulk_role_update',
        'user_role',
        target_user_id,
        jsonb_build_object(
          'new_role', new_role,
          'performer_id', performer_id,
          'timestamp', now()
        )
      );
    END IF;
  END LOOP;
  
  RETURN jsonb_build_object(
    'success', true,
    'updated_count', updated_count,
    'message', format('Successfully updated %s user roles', updated_count)
  );
END;
$function$;

-- verify: bulk_update_user_roles_secure now references is_tenant_owner
