INSERT INTO gw_syllabus_templates (
  course_id,
  name,
  term,
  instructor_name,
  instructor_email,
  instructor_phone,
  instructor_office,
  office_hours,
  class_time,
  classroom,
  credits,
  purpose,
  grading_breakdown,
  grading_scale,
  attendance_policy,
  late_assignment_policy,
  academic_honesty_policy,
  disability_statement,
  weekly_schedule,
  is_published
) VALUES (
  'a0000000-0000-0000-0000-000000000070',
  'MUS 070 Course Syllabus',
  'Spring 2026',
  'Dr. Kevin Johnson',
  'kjohns10@spelman.edu',
  '470-622-1392',
  'Fine Arts 105',
  'Monday & Wednesday, 12:00–1:00 PM (or by appointment)',
  'MWF 11:00am - 12:15pm',
  'Sisters Chapel',
  '1',
  'This course is designed to prepare and perform appropriate choral literature at the highest possible level, and to represent Spelman College in public performance. Students will learn proper and healthy singing techniques, musical terms, and choral concepts. Through rehearsals and performances, members develop musicianship, teamwork, and cultural appreciation while upholding the Glee Club''s 100+ year legacy of excellence.',
  '[
    {"category": "Performances", "percentage": 50},
    {"category": "Attendance & Participation", "percentage": 25},
    {"category": "Sight-Singing Quizzes", "percentage": 15},
    {"category": "Concert Attire & Preparation", "percentage": 10}
  ]',
  '{"A": "90-100", "B": "80-89", "C": "70-79", "D": "60-69", "F": "Below 60"}',
  'Attendance at all rehearsals and performances is mandatory. Each student is allowed to miss two rehearsals with no penalty. Any absence beyond two lowers the grade by one letter grade. Students who miss four rehearsals will be dropped from the class. Performance absences require prior approval and documentation. It is the student''s responsibility to communicate with the director when there is a problem.',
  'All assignments including music memorization, uniform preparation, and repertoire learning must be completed by the specified deadlines. Late preparation affects ensemble quality and will impact participation grades.',
  'The Spelman College community is committed to maintaining the integrity of the College and its academic programs. Each student is required to abide by Spelman''s code of conduct and is expected to produce work that reflects her own ideas.',
  'Any student who feels she may need an accommodation based on the impact of a disability should contact the Office of Disability Services privately to discuss her specific needs. Please contact the Office of Disability Services at (404) 223-7590 in MacVicar Hall to coordinate reasonable accommodations.',
  '[
    {"week": "Week 1", "topics": "Welcome & Orientation", "readings": "Handbook review, voice part assignments", "assignments": "Complete voice placement assessment"},
    {"week": "Week 2-3", "topics": "Fall Repertoire Introduction", "readings": "New music distribution", "assignments": "Begin music memorization, Sight-singing Quiz 1"},
    {"week": "Week 4-5", "topics": "Vocal Technique & Blend", "readings": "Breathing exercises, vowel unification", "assignments": "Section rehearsals, Sight-singing Quiz 2"},
    {"week": "Week 6-7", "topics": "Musicality & Expression", "readings": "Dynamics, phrasing, text painting", "assignments": "Full ensemble rehearsals"},
    {"week": "Week 8", "topics": "Mid-Semester Performance Prep", "readings": "Performance etiquette review", "assignments": "Dress rehearsal, Concert #1"},
    {"week": "Week 9-10", "topics": "Spring Repertoire Introduction", "readings": "New music distribution", "assignments": "Begin spring memorization, Sight-singing Quiz 3"},
    {"week": "Week 11-12", "topics": "Tour Preparation", "readings": "Tour repertoire intensive", "assignments": "Extended rehearsals, travel logistics"},
    {"week": "Week 13", "topics": "Spring Tour", "readings": "Performance venues", "assignments": "Tour performances"},
    {"week": "Week 14-15", "topics": "Final Concert Preparation", "readings": "Spring concert repertoire", "assignments": "Dress rehearsals, Spring Concert"}
  ]',
  true
);